// Code generated by "stringer -type=BinaryOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Addition-0]
	_ = x[Subtraction-1]
	_ = x[Multiplication-2]
	_ = x[Division-3]
	_ = x[Modulo-4]
	_ = x[Equality-5]
	_ = x[Inequality-6]
	_ = x[Less-7]
	_ = x[Greater-8]
	_ = x[LessEqual-9]
	_ = x[GreaterEqual-10]
	_ = x[ShiftLeft-11]
	_ = x[ShiftRight-12]
	_ = x[LogicAnd-13]
	_ = x[LogicOr-14]
}

const _BinaryOperator_name = "AdditionSubtractionMultiplicationDivisionModuloEqualityInequalityLessGreaterLessEqualGreaterEqualShiftLeftShiftRightLogicAndLogicOr"

var _BinaryOperator_index = [...]uint8{0, 8, 19, 33, 41, 47, 55, 65, 69, 76, 85, 97, 106, 116, 124, 131}

func (i BinaryOperator) String() string {
	if i < 0 || i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
