// Code generated by "stringer -type=BinaryOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Addition-0]
	_ = x[Subtraction-1]
	_ = x[Multiplication-2]
	_ = x[Division-3]
	_ = x[Equality-4]
	_ = x[Inequality-5]
	_ = x[Less-6]
	_ = x[Greater-7]
	_ = x[LessEqual-8]
	_ = x[GreaterEqual-9]
	_ = x[ShiftLeft-10]
	_ = x[ShiftRight-11]
	_ = x[LogicAnd-12]
	_ = x[LogicOr-13]
}

const _BinaryOperator_name = "AdditionSubtractionMultiplicationDivisionEqualityInequalityLessGreaterLessEqualGreaterEqualShiftLeftShiftRightLogicAndLogicOr"

var _BinaryOperator_index = [...]uint8{0, 8, 19, 33, 41, 49, 59, 63, 70, 79, 91, 100, 110, 118, 125}

func (i BinaryOperator) String() string {
	if i < 0 || i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
