// Code generated by "stringer -type=BinaryOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Addition-0]
	_ = x[Subtraction-1]
	_ = x[Multiplication-2]
	_ = x[Division-3]
	_ = x[Equality-4]
	_ = x[LessThan-5]
	_ = x[GreaterThan-6]
	_ = x[LessThanEqual-7]
	_ = x[GreaterThanEqual-8]
	_ = x[LogicAnd-9]
	_ = x[LogicOr-10]
}

const _BinaryOperator_name = "AdditionSubtractionMultiplicationDivisionEqualityLessThanGreaterThanLessThanEqualGreaterThanEqualLogicAndLogicOr"

var _BinaryOperator_index = [...]uint8{0, 8, 19, 33, 41, 49, 57, 68, 81, 97, 105, 112}

func (i BinaryOperator) String() string {
	if i < 0 || i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
