// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Literal-0]
	_ = x[Keyword-1]
	_ = x[Operator-2]
	_ = x[Identifier-3]
	_ = x[Punctuator-4]
}

const _TokenKind_name = "LiteralKeywordOperatorIdentifierPunctuator"

var _TokenKind_index = [...]uint8{0, 7, 14, 22, 32, 42}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
